version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: fluentai_db
      POSTGRES_USER: fluentai_admin
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: brainiac2677/fluentai:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fluentai_db
      SPRING_DATASOURCE_USERNAME: fluentai_admin
      SPRING_DATASOURCE_PASSWORD: 1234567
    depends_on:
      - postgres

volumes:
  pgdata:
