name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - backend/**  # Trigger on changes in the backend folder
  pull_request:
    branches:
      - main
    paths:
      - backend/**  # Trigger on PRs affecting the backend folder

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        working-directory: backend  # Change to backend directory
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: mvn clean package

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: fluentai-backend-jar  # Updated JAR name
          path: backend/target/fluentai-0.0.1-SNAPSHOT.jar

  docker_build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: fluentai-backend-jar  # Match the updated JAR name
          path: ./backend/target

      - name: Build Docker Image
        run: docker build -t registry.digitalocean.com/fluentai/fluentai-backend:latest ./backend  # Specify backend folder

      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login registry.digitalocean.com -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push registry.digitalocean.com/fluentai/fluentai-backend:latest
