name: Frontend CI/CD Pipeline

on:
  push:
    paths:
      - 'frontend/**' # Only trigger on changes in the frontend directory
  pull_request:
    paths:
      - 'frontend/**' # Trigger on pull requests affecting the frontend directory

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Build Docker image (no need to build the Next.js project separately)
      - name: Build Docker Image
        run: docker build -t registry.digitalocean.com/fluentai/fluentai-frontend:latest ./frontend

      # Log in to DigitalOcean Container Registry
      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login registry.digitalocean.com -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      # Push Docker image to DigitalOcean Container Registry
      - name: Push Docker Image
        run: docker push registry.digitalocean.com/fluentai/fluentai-frontend:latest
